# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160731005009 on 2016-08-18 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='url',
        ),
    ]
