# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160731005009 on 2016-08-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_remove_movies_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
