# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160731005009 on 2016-08-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_movies_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Movies')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
